### ISSUE TITLE
`ko_build` module hell 

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/terraform-provider-ko#5]
I was trying to put together a terraform module using this to package up and deploy an application.

The application and terraform module live in `foo/` which has its own `go.mod` file.

Then from `bar/` I reference the above terraform module:
```
module "foo" {
   source = "../foo"
}
```

However, this blows up (I believe) because in the context of `bar/` the `importpath` referenced by the `ko_build` in `foo/` doesn't make sense.

It would be nice to be able to tell `ko_build` to execute in the context of `foo/` so that we can use terraform modules to encapsulate complete source-based deployments 🤩 

cc @imjasonh @nsmith5 

---

Aside: I'd be happy to try my hand at this, but haven't the first clue where to begin

**Comment by nsmith5** [comment]
This can likely be fixed with the use of the `${path.module}` variable in your ko terraform module. See the docs here for reference: https://www.terraform.io/language/expressions/references#filesystem-and-workspace-info. 

`path.module` is the full path (I believe) of where the module has been defined. So if you're trying to build `./cmd/baz` relative to the module you can do the following:

```terraform
resource "ko_image" {
  importpath = "${path.module}/cmd/baz"
}
```

**Comment by mattmoor** [comment]
@nsmith5 I'm not sure that plays nicely with how Go expects import paths to be shaped, but perhaps `ko_image` could take a working directory argument that we could use this in. 🤔

**Comment by mattmoor** [comment]
the combination of Jason's change with Nathan's magic variable seems to work for me!

**Comment by mattmoor** [comment]
Yeah, I'm waiting to push a PR until we publish this :D
